### ISSUE TITLE
Cant control Beolab 2000 from HA

### ISSUE THREAD

**Issue by oskarax** [giachello/mlgw#5]
Hi!

All my speakers except my Beolab 2000 is controllable through HA. I get this fault in the logs.

2021-03-23 21:03:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2784522568] list index out of range
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 550, in async_turn_on
await self.hass.async_add_executor_job(self.turn_on)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/mlgw/media_player.py", line 540, in turn_on
% (self._gateway.beolink_source, self._source, self._source_names[0])
IndexError: list index out of range

Not sure what it means. I haven't done anything different with this config.

**Comment by giachello** [comment]
Did you configure any sources for the beolab 2000? the error is saying there are no sources listed for that speaker.

**Comment by oskarax** [comment]
Can't remember configuring any sources with the other products. Since a changed from old setup to the new it configured itself. Or maybe I'm mistaken?

**Comment by oskarax** [comment]
Sorry, I think I get it now. I didn't need to do that with old config but now I remember that I need to configure sources in masterlink gateway.

**Comment by giachello** [comment]
Ok that seems to have fixed the issue. I will add a check on that line of code to avoid the error and give a more informative error message to the user.

**Comment by oskarax** [comment]
No problem! Let me know if there is anything else I can assist with. I'm using your integration everyday and I'm very happy with it so far.
